name: caller

on: workflow_dispatch

jobs:
  callstep1:
    uses: ./.github/workflows/test.yml
  echoer:
    runs-on: ubuntu-latest
    needs: callstep1
    steps:
    - id: step1
      run: |
        pwd
        ls -l
    - id: step2
      run: echo ${{needs.callstep1.outputs.buildout}}
    
    
