name: caller

on: workflow_dispatch

jobs:
  callstep1:
    uses: ./.github/workflows/test.yml
  echoer:
    runs-on: ubuntu-latest
    needs: callstep1
    steps:
    - run: echo ${{needs.callstep1.outputs.out1}}
    
    
