name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: ubuntu
          options: -v ${{ github.workspace }}:/work
          run: |
            touch /work/afile
      - uses: addnab/docker-run-action@v3
        with:
          image: ubuntu
          options: -v ${{ github.workspace }}:/work
          run: |
            ls -l /work/afile
