name: CI
on: [push, pull_request,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.step2.outputs.out1}}
    steps:
      - uses: actions/checkout@v3
      - id: step2
        run: echo "out1=test" >> ${GITHUB_OUTPUT}
