name: CI
on: 
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      buildout: 
        value: ${{jobs.build.outputs.test}}
    

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.step2.outputs.out1}}
    steps:
      - uses: actions/checkout@v3
      - id: step2
        shell: python
        run: |
          import os
          with open(os.environ["GITHUB_OUTPUT"], "a+") as fout:
            fout.write("out1={}".format("test"))
      - id: step3
        run: |
          pwd
          touch afile
          ls -l
      - id: step4
        uses: actions/upload-artifact@v3
        with:
          name: afile
          path: ${{github.workspace}}/afile
  next:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{needs.build.outputs.test}}
