name: CI
on: 
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      buildout: 
        value: ${{jobs.build.outputs.test}}
    

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.step2.outputs.out1}}
    steps:
      - uses: actions/checkout@v3
      - id: step2
        run: echo "out1=test" >> ${GITHUB_OUTPUT}
  next:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{needs.build.outputs.test}}
