name: CI
on: 
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      buildout: 
        value: ${{jobs.build.outputs.test}}
    

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test: ${{steps.step2.outputs.out1}}
      here: ${{steps.step2a.outputs.here}}
    steps:
      - uses: actions/checkout@v3
      - id: step2
        shell: python
        run: |
          import os
          with open(os.environ["GITHUB_OUTPUT"], "a+") as fout:
            fout.write("out1={}".format("test"))
      - id: step2a
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu
          run: |
            apt update
            apt -y install python3-pip
            echo ${GITHUB_OUTPUT}
            python3 -c 'print("here=here")' >> ${GITHUB_OUTPUT}
      - id: step3
        run: |
          pwd
          touch afile
          ls -l
      - id: step4
        uses: actions/upload-artifact@v3
        with:
          name: afile
          path: ${{github.workspace}}/afile
  next:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{needs.build.outputs.test}}
